package BookMyShowApp;


/**
* BookMyShowApp/BookingInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BookingInterface.idl
* Thursday, February 23, 2023 12:48:40 o'clock AM EST
*/

public interface BookingInterface extends BookingInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface BookingInterface
