package BookMyShowApp;


/**
* BookMyShowApp/BookingInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BookingInterface.idl
* Monday, March 6, 2023 8:55:39 o'clock PM EST
*/

abstract public class BookingInterfaceHelper
{
  private static String  _id = "IDL:BookMyShowApp/BookingInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, BookMyShowApp.BookingInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static BookMyShowApp.BookingInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (BookMyShowApp.BookingInterfaceHelper.id (), "BookingInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static BookMyShowApp.BookingInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_BookingInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, BookMyShowApp.BookingInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static BookMyShowApp.BookingInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof BookMyShowApp.BookingInterface)
      return (BookMyShowApp.BookingInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      BookMyShowApp._BookingInterfaceStub stub = new BookMyShowApp._BookingInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static BookMyShowApp.BookingInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof BookMyShowApp.BookingInterface)
      return (BookMyShowApp.BookingInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      BookMyShowApp._BookingInterfaceStub stub = new BookMyShowApp._BookingInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
