package BookMyShowApp;

/**
* BookMyShowApp/BookingInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BookingInterface.idl
* Thursday, February 23, 2023 12:48:40 o'clock AM EST
*/

public final class BookingInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public BookMyShowApp.BookingInterface value = null;

  public BookingInterfaceHolder ()
  {
  }

  public BookingInterfaceHolder (BookMyShowApp.BookingInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BookMyShowApp.BookingInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BookMyShowApp.BookingInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BookMyShowApp.BookingInterfaceHelper.type ();
  }

}
