package BookMyShowApp;


/**
* BookMyShowApp/BookingInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BookingInterface.idl
* Monday, March 6, 2023 8:55:39 o'clock PM EST
*/

public interface BookingInterfaceOperations 
{

  // Admin
  String addMovieSlots (String movieID, String movieName, int bookingCapacity);
  String removeMovieSlots (String movieID, String movieName);
  String[] listMovieShowsAvailability (String movieName, boolean isClientCall);

  // Customer
  String bookMovieTickets (String customerID, String movieID, String movieName, int numberOfTickets, boolean isClientCall);
  String[] getBookingSchedule (String customerID, boolean isClientCall);
  String cancelMovieTickets (String customerID, String movieID, String movieName, int numberOfTickets, boolean isClient);
  String exchangeTickets (String customerID, String curr_movieID, String new_movieID, String new_movieName, int numberOfTickets);
  void shutdown ();
} // interface BookingInterfaceOperations
