package BookMyShowApp;


/**
* BookMyShowApp/BookingInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BookingInterface.idl
* Monday, March 6, 2023 8:55:39 o'clock PM EST
*/

public abstract class BookingInterfacePOA extends org.omg.PortableServer.Servant
 implements BookMyShowApp.BookingInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addMovieSlots", new java.lang.Integer (0));
    _methods.put ("removeMovieSlots", new java.lang.Integer (1));
    _methods.put ("listMovieShowsAvailability", new java.lang.Integer (2));
    _methods.put ("bookMovieTickets", new java.lang.Integer (3));
    _methods.put ("getBookingSchedule", new java.lang.Integer (4));
    _methods.put ("cancelMovieTickets", new java.lang.Integer (5));
    _methods.put ("exchangeTickets", new java.lang.Integer (6));
    _methods.put ("shutdown", new java.lang.Integer (7));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // Admin
       case 0:  // BookMyShowApp/BookingInterface/addMovieSlots
       {
         String movieID = in.read_string ();
         String movieName = in.read_string ();
         int bookingCapacity = in.read_long ();
         String $result = null;
         $result = this.addMovieSlots (movieID, movieName, bookingCapacity);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // BookMyShowApp/BookingInterface/removeMovieSlots
       {
         String movieID = in.read_string ();
         String movieName = in.read_string ();
         String $result = null;
         $result = this.removeMovieSlots (movieID, movieName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // BookMyShowApp/BookingInterface/listMovieShowsAvailability
       {
         String movieName = in.read_string ();
         boolean isClientCall = in.read_boolean ();
         String $result[] = null;
         $result = this.listMovieShowsAvailability (movieName, isClientCall);
         out = $rh.createReply();
         BookMyShowApp.MovieAvailabilityHelper.write (out, $result);
         break;
       }


  // Customer
       case 3:  // BookMyShowApp/BookingInterface/bookMovieTickets
       {
         String customerID = in.read_string ();
         String movieID = in.read_string ();
         String movieName = in.read_string ();
         int numberOfTickets = in.read_long ();
         boolean isClientCall = in.read_boolean ();
         String $result = null;
         $result = this.bookMovieTickets (customerID, movieID, movieName, numberOfTickets, isClientCall);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // BookMyShowApp/BookingInterface/getBookingSchedule
       {
         String customerID = in.read_string ();
         boolean isClientCall = in.read_boolean ();
         String $result[] = null;
         $result = this.getBookingSchedule (customerID, isClientCall);
         out = $rh.createReply();
         BookMyShowApp.MoviesBookedHelper.write (out, $result);
         break;
       }

       case 5:  // BookMyShowApp/BookingInterface/cancelMovieTickets
       {
         String customerID = in.read_string ();
         String movieID = in.read_string ();
         String movieName = in.read_string ();
         int numberOfTickets = in.read_long ();
         boolean isClient = in.read_boolean ();
         String $result = null;
         $result = this.cancelMovieTickets (customerID, movieID, movieName, numberOfTickets, isClient);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // BookMyShowApp/BookingInterface/exchangeTickets
       {
         String customerID = in.read_string ();
         String curr_movieID = in.read_string ();
         String new_movieID = in.read_string ();
         String new_movieName = in.read_string ();
         int numberOfTickets = in.read_long ();
         String $result = null;
         $result = this.exchangeTickets (customerID, curr_movieID, new_movieID, new_movieName, numberOfTickets);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // BookMyShowApp/BookingInterface/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:BookMyShowApp/BookingInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public BookingInterface _this() 
  {
    return BookingInterfaceHelper.narrow(
    super._this_object());
  }

  public BookingInterface _this(org.omg.CORBA.ORB orb) 
  {
    return BookingInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class BookingInterfacePOA
