package BookMyShowApp;


/**
* BookMyShowApp/MovieAvailabilityHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BookingInterface.idl
* Monday, March 6, 2023 8:55:39 o'clock PM EST
*/

public final class MovieAvailabilityHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public MovieAvailabilityHolder ()
  {
  }

  public MovieAvailabilityHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BookMyShowApp.MovieAvailabilityHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BookMyShowApp.MovieAvailabilityHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BookMyShowApp.MovieAvailabilityHelper.type ();
  }

}
