package BookMyShowApp;


/**
* BookMyShowApp/MoviesBookedHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BookingInterface.idl
* Monday, March 6, 2023 8:55:39 o'clock PM EST
*/

public final class MoviesBookedHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public MoviesBookedHolder ()
  {
  }

  public MoviesBookedHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BookMyShowApp.MoviesBookedHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BookMyShowApp.MoviesBookedHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BookMyShowApp.MoviesBookedHelper.type ();
  }

}
